import Head from "next/head";
import { useRouter } from 'next/router';  

import styles from "@/styles/Cardapio.module.css";  
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';  

export default function Cardapio() {
    const router = useRouter();  
    const { user } = router.query;

    return (
        <>
            <Head>
                <title>Cardapio-delivery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div>
                    <h1>Bem vindo(a), {user}!</h1>
                </div>

            </main>
        </>
    )
}