import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cardapio-delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
        <div className="">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYVG2gpz84zCp-3Fr4zZxHgfLeqxgbe_JUZw&s" alt="Logo da PrefiroDelivery"/>
          <h1>Entre na sua conta para começar.</h1>
        </div>

        <div className={styles.form}>
        <input type="text" placeholder="Usuário/E-mail* " required />
        <input type="password" placeholder="Senha*" required/>

        <button type="submit">Enviar</button>
        </div>
      </main>
    </>
  );
}
